### PR TITLE
Allow the directive to implement a User service with a different name than "User"

### PR DESCRIPTION
**Pull request by Turom**
Added the ability to inject a different User service than "User" in case you have a different name for this service in the application.

### CODE REVIEW

**Comment by antleblanc** [comment]
@Turom Thx.
Do not hesitate to use some commit message convention (ref: https://github.com/ovh-ux/ovh-ux-guidelines/blob/master/.github/CONTRIBUTING.md#tldr).

**Comment by Turom** [comment]
@antleblanc Oops! Will do next time!

**Comment by ghost** [comment]
@Turom you can use this tool https://github.com/ovh-ux/cz-ovh-commit

and you can do git rebase -i to respect our convention :)

**Review by ghost — CHANGES_REQUESTED** [review]
this pull request does not respect our guidelines

**Review by ghost — APPROVED** [review]

**Pull request merged**
